# Generated by Django 4.2.12 on 2024-05-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Add_camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("make", models.CharField(max_length=20)),
                ("camera_model", models.CharField(max_length=30)),
                ("zoom", models.IntegerField()),
                ("ip", models.GenericIPAddressField()),
            ],
        ),
    ]
