# Generated by Django 5.0.6 on 2024-05-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('alert', models.CharField(max_length=30)),
                ('camera_number', models.IntegerField()),
                ('transition', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Add_camera',
        ),
    ]
