# Generated by Django 5.0.6 on 2024-05-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alert_log_delete_add_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_log',
            name='transition',
        ),
        migrations.AddField(
            model_name='alert_log',
            name='clip_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
